[package]
name = "wcp"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.5.10"
rayon = "1.7"
crossbeam = "0.8"
clap = { version = "4.3", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
